---
title: "Commits"
output:
  pdf_document:
    latex_engine: pdflatex
---


```{r}
system("git add .")
system("git commit -m \"Laboratorio 2\" ")
system("git push")
```
```{r}
system("git add .")
system("git commit -m \"Laboratorio 2\" ")
system("git push")
```



# Comandos para que R pueda crear los pdf automaticamente utilizando Mixtext

library(tinytex)
tinytex::install_tinytex()


```{r}
system("git add .")
system("git commit -m \"configuracion de PDF\" ")
system("git push")
```
```{r}
system("git add .")
system("git commit -m \"1. Cree un conjunto de columnas nuevas:\" ")
system("git push")
```


```{r}
system("git add .")
system("git commit -m \"2. ¿Qué mes es el que tiene la mayor demanda?\" ")
system("git push")
```
```{r}
system("git add .")
system("git commit -m \"3. ¿Qué rango de hora es la de mayor demanda? Muestre una tabla y una gráfica\" ")
system("git push")
```

```{r}
system("git add .")
system("git commit -m \"4. ¿Qué temporada es la mas alta? Muestre una tabla.\" ")
system("git push")
```


```{r}
system("git add .")
system("git commit -m \"5\" ")
system("git push")
```


```{r}
system("git add .")
system("git commit -m \"6\" ")
system("git push")
```


```{r}
system("git add .")
system("git commit -m \"7\" ")
system("git push")
```



```{r}
system("git add .")
system("git commit -m \"8\" ")
system("git push")
```


